[package]
name = "hyprspace-update"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
futures.workspace = true
reqwest = { workspace = true, features = ["stream"] }
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
minisign-verify = "0.2"
semver = "1"
flate2 = "1"
tar = "0.4"

[dev-dependencies]
minisign = "0.7"
tokio.workspace = true
