// Bake xterm.js + its CSS into one self-contained HTML string for the terminal WebView.
//
// Why generated rather than a runtime dependency: the WebView has to work with no network (it's
// mirroring a terminal over your LAN, sometimes with no internet at all), and shipping the page as
// one inlined string sidesteps native asset plumbing entirely. xterm comes from the DESKTOP app's
// node_modules, so both halves render with the exact same emulator version.
//
//   node scripts/build-term.mjs      (also runs via `npm run term`)

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");
const out = join(here, "..", "src", "terminal", "termHtml.ts");

const js = readFileSync(join(root, "node_modules", "@xterm", "xterm", "lib", "xterm.js"), "utf8");
const css = readFileSync(join(root, "node_modules", "@xterm", "xterm", "css", "xterm.css"), "utf8");

// a literal </script> inside the bundle would end the tag early; \/ is the same string to JS
const safeJs = js.replace(/<\/script/gi, "<\\/script");

const page = `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
<style>
${css}
html, body {
  margin: 0;
  padding: 0;
  background: #161616;
  overflow: hidden;
  -webkit-user-select: none;
  user-select: none;
}
/* the mirror renders at the DESKTOP's cols/rows and is then scaled to fit the phone, so what you
   see is the same screen the desktop is showing rather than a reflowed approximation */
#wrap { position: absolute; inset: 0; overflow: auto; -webkit-overflow-scrolling: touch; }
#term { transform-origin: top left; }
.xterm .xterm-viewport { background: transparent !important; overflow-y: hidden !important; }
</style>
</head>
<body>
<div id="wrap"><div id="term"></div></div>
<script>${safeJs}</script>
<script>
(function () {
  var host = document.getElementById("term");
  var wrap = document.getElementById("wrap");
  var zoom = 1;

  var term = new Terminal({
    // display-only: keystrokes travel over the bridge, not through this canvas
    disableStdin: true,
    cursorBlink: false,
    scrollback: 4000,
    fontFamily: 'monospace',
    fontSize: 13,
    lineHeight: 1.1,
    allowProposedApi: true,
    theme: {
      background: "#161616", foreground: "#f5f5f5", cursor: "#f5f5f5",
      selectionBackground: "rgba(255,255,255,0.18)",
      black: "#161616", red: "#ef4444", green: "#10b981", yellow: "#f59e0b",
      blue: "#3b82f6", magenta: "#a855f7", cyan: "#22d3ee", white: "#d4d4d4",
      brightBlack: "#767676", brightRed: "#f87171", brightGreen: "#34d399",
      brightYellow: "#fbbf24", brightBlue: "#60a5fa", brightMagenta: "#c084fc",
      brightCyan: "#67e8f9", brightWhite: "#f5f5f5"
    }
  });
  term.open(host);

  function fit() {
    host.style.transform = "scale(1)";
    var w = host.offsetWidth || 1;
    var k = Math.min(1, window.innerWidth / w) * zoom;
    host.style.transform = "scale(" + k + ")";
    // the scaled box no longer drives layout, so give the scroller the real size
    host.style.marginBottom = (host.offsetHeight * k - host.offsetHeight) + "px";
    host.style.marginRight = (host.offsetWidth * k - host.offsetWidth) + "px";
  }

  // base64 → bytes. term.write takes a Uint8Array, so the raw PTY stream (escape sequences and
  // all) goes straight in without a lossy trip through a JS string.
  var TBL = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  var REV = {};
  for (var i = 0; i < TBL.length; i++) REV[TBL[i]] = i;
  function decode(s) {
    var clean = s.replace(/[^A-Za-z0-9+/]/g, "");
    var n = clean.length;
    var bytes = new Uint8Array((n * 3) >> 2);
    var o = 0, acc = 0, bits = 0;
    for (var j = 0; j < n; j++) {
      acc = (acc << 6) | REV[clean[j]];
      bits += 6;
      if (bits >= 8) { bits -= 8; bytes[o++] = (acc >> bits) & 255; }
    }
    return bytes.subarray(0, o);
  }

  window.hsWrite = function (b64) { term.write(decode(b64)); };
  window.hsResize = function (cols, rows) { term.resize(cols, rows); fit(); };
  window.hsZoom = function (z) { zoom = z; fit(); };
  window.hsClear = function () { term.reset(); };
  window.hsBottom = function () { term.scrollToBottom(); wrap.scrollTop = wrap.scrollHeight; };

  window.addEventListener("resize", fit);
  fit();
  if (window.ReactNativeWebView) window.ReactNativeWebView.postMessage("ready");
})();
</script>
</body>
</html>
`;

mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// GENERATED by scripts/build-term.mjs — do not edit. Re-run \`npm run term\` after upgrading
// @xterm/xterm in the desktop app, so both halves render with the same emulator.
export const TERM_HTML = ${JSON.stringify(page)};
`,
  "utf8",
);

console.log(`wrote ${out} (${(page.length / 1024).toFixed(0)} KB)`);
